#
#  ▄▄█▀▀▀█▄█▀████▄     ▄███▀███▀▀▀██▄ ▀████▀███▀▀▀██▄
#▄██▀     ▀█  ████    ████   ██    ▀██▄ ██   ██    ▀██▄
#██▀       ▀  █ ██   ▄█ ██   ██     ▀██ ██   ██     ▀██ ▄▄█▀██▀██▀   ▀██▀
#██           █  ██  █▀ ██   ██      ██ ██   ██      ██▄█▀   ██ ██   ▄█
#██▄    ▀████ █  ██▄█▀  ██   ██     ▄██ ██   ██     ▄████▀▀▀▀▀▀  ██ ▄█
#▀██▄     ██  █  ▀██▀   ██   ██    ▄██▀ ██   ██    ▄██▀██▄    ▄   ███
#  ▀▀███████▄███▄ ▀▀  ▄████▄████████▀ ▄████▄████████▀   ▀█████▀    █
#
# Plugin creato da @GabryOsas / @GMDIdevelopment
QAProiettile:
  Title: "&cFerite da Proiettile"
  SubTitle: "&7Sei stato colpito da un proiettile!"
  Bisturi: "&bBisturi"
  Material: STICK
  Credits: true