#
#  ▄▄█▀▀▀█▄█▀████▄     ▄███▀███▀▀▀██▄ ▀████▀███▀▀▀██▄
#▄██▀     ▀█  ████    ████   ██    ▀██▄ ██   ██    ▀██▄
#██▀       ▀  █ ██   ▄█ ██   ██     ▀██ ██   ██     ▀██ ▄▄█▀██▀██▀   ▀██▀
#██           █  ██  █▀ ██   ██      ██ ██   ██      ██▄█▀   ██ ██   ▄█
#██▄    ▀████ █  ██▄█▀  ██   ██     ▄██ ██   ██     ▄████▀▀▀▀▀▀  ██ ▄█
#▀██▄     ██  █  ▀██▀   ██   ██    ▄██▀ ██   ██    ▄██▀██▄    ▄   ███
#  ▀▀███████▄███▄ ▀▀  ▄████▄████████▀ ▄████▄████████▀   ▀█████▀    █
#
# Plugin creato da @GabryOsas / @GMDIdevelopment
QAProiettile:
  Title: "&cFerite da Proiettile"
  SubTitle: "&7Sei stato colpito da un proiettile!"
  Bisturi: "&bBisturi"
  Material: STICK
  Credits: true
Message:
  NoPerms: "&cNon hai abbastanza permessi!"
  Give: "&aItem givvato con successo!"
  Jump: "&cSei ferito da un proiettile, di conseguenza non puoi saltare!"
  Revive: "&aHai guarito il giocatore!"
  NoDamage: "&cIl giocatore non è ferito!"