#
# ▄▄█▀▀██       █     ▀██▀▀█▄                   ██            ▄     ▄    ██  ▀██
#▄█▀    ██     ███     ██   ██ ▄▄▄ ▄▄    ▄▄▄   ▄▄▄    ▄▄▄▄  ▄██▄  ▄██▄  ▄▄▄   ██    ▄▄▄▄
#██      ██   █  ██    ██▄▄▄█▀  ██▀ ▀▀ ▄█  ▀█▄  ██  ▄█▄▄▄██  ██    ██    ██   ██  ▄█▄▄▄██
#▀█▄  ▀▄ ▀█  ▄▀▀▀▀█▄   ██       ██     ██   ██  ██  ██       ██    ██    ██   ██  ██
#  ▀█▄▄▄▀█▄ ▄█▄  ▄██▄ ▄██▄     ▄██▄     ▀█▄▄█▀ ▄██▄  ▀█▄▄▄▀  ▀█▄▀  ▀█▄▀ ▄██▄ ▄██▄  ▀█▄▄▄▀
#
#Plugin creato da GabryOsas / GMDIdevelopment
#Sorry for my bad English...
QAProiettile:
  Items:
    Name: "&bBisturi"
    Material: STICK
    Costum-Model-Data: 1
    Lore:
      - "&7Utilizzalo per guarire le persone!"
  Boolean:
    Update: true
    Credits: true
    Anti-Jump: true
    Remove-On-Death: true
  Title: "&cFerite da Proiettile"
  Sub-Title: "&7Sei stato colpito da un proiettile!"
  Blacklist-Gun:
    - "ak47"
  Blacklist-World:
    - "world_nether"
    - "world_the_end"
Message:
  No-Perms: "&cNon hai abbastanza permessi!"
  Give: "&aItem givvato con successo!"
  Jump: "&cSei ferito da un proiettile, di conseguenza non puoi saltare!"
  Revive: "&aHai guarito il giocatore &e%target%!"
  Target-Revive: "&aSei stato guarito da &e%player%"
  No-Damage: "&cIl giocatore &e%target% &cnon è ferito!"
  Reload: "&aPlugin ricaricato con successo!"
  Anti-Console: "&cNon puoi eseguire questo comando dalla console!"
  Update-True: "&aCi sono nuovi aggiornamenti! Scarica la nuova versione dal seguente link: %link%"
  Update-False: "&cNon ci sono aggiornamenti al momento."
Events: #You cannot add other events you can only edit them ;P
  potion-events:
    Enable: true
    Every: 10 #In seconds
    Effects:
      - SLOW, 1, 5 #level and time
      - BLINDNESS, 1, 5
Permission:
  Scalpel-Perms: "qaproiettile.scalpel.give"
  Reload-Perms: "qaproiettile.reload.use"
  Override-Perms: "qaproiettile.hit.override"
